### ISSUE TITLE
How to you achieve this same result with iOS?

### ISSUE THREAD

**Issue by danielweinmann** [luggg/react-native-android-config#1]
I know this is not an issue with this package itself, but I couldn't find anything similar for iOS so far. I'm new to native stuff, so I might be missing something obvious.

Do you know of any way to expose precompiler macros like DEBUG to javascript in RN + iOS?

Anyway, I was missing some 12 factor love working with RN :) thanks for this package!

**Comment by danielweinmann** [comment]
@pedro, can you help with this?

**Comment by pedro** [comment]
Hi Daniel,

Good question, figured I'd explore this next time we're making an iOS app with React Native. For that I saved this in hopes it would be helpful:

http://www.fabiancanas.com/blog/2014/9/1/keeping-private-api-keys-private

Let me know if you can get it to work! We could then rename this to just `react-native-config`, or at least I'd link to your version of `react-native-ios-config`.

Thanks,

**Comment by pedro** [comment]
Closing for now but keep me updated!
